baseURL: "https://blog.jzhao.xyz"
languageCode: "en-us"
title: "jacky zhao | blog"
footnoteReturnLinkContents: "â†©"

params:
    headline: "jzhao.xyz"
    github: "https://github.com/jackyzha0"
    twitter: "https://twitter.com/_jzhao"
    email: "j.zhao2k19@gmail.com"
    author: "jacky"